name: casa
channels:
  - defaults
  - conda-forge
  - astropy

dependencies:
  - python=3.6
  - astropy=4.0
  - cython=0.29.14
  - h5py=2.10.0
  - matplotlib=3.3.2
  - numba=0.47.0
  - numpy=1.19.2
  - pandas=0.25.3
  - pytest=5.3.2
  - coverage=5.0
  - codecov=2.1.3
  - scipy=1.4.1
  - click=7.0
  - pyyaml=5.1.2
  - pylint
  - pip
