name: casa6
channels:
  - conda-forge
  - astropy
  - defaults

dependencies:
  - python=3.6
  - astropy=4.0
  - cython=0.29.14
  - h5py=2.10.0
  - matplotlib=2.2.4
  - numba=0.47.0
  - numpy=1.17.5
  - pandas=0.25.
  - pytest=5.3.2
  - scipy=1.4.1